spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authserverdb?useSSL=false&serverTimezone=UTC
    username: root
    password: mysql123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

#security:
#  oauth2:
#    resource:
#      jwk:
#        key-set-uri: /.well-known/jwks.json

